specVersion: 1.0.0
name: relaychain-subql
version: 0.0.2
runner:
  node:
    name: '@subql/node'
    version: v0.33.0
  query:
    name: '@subql/query'
    version: v0.14.1
description: Parallel kusama/polkadot subql indexing service
repository: 'https://github.com/parallel-finance/relaychain-subql'
schema:
  file: ./schema.graphql
network:
  chainId: '0xf86591aeaa54b7221022a95b298d1bdf68603cb689d555bd4d686ecc4a83ba2c'
  endpoint: 'wss://regnet4-relay-rpc.parallel.fi'
dataSources:
  - kind: substrate/Runtime
    startBlock: 15000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
