specVersion: 0.2.0
name: relaychain-subql
version: 0.0.1
description: Parallel kusama/polkadot subql indexing service
repository: 'https://github.com/parallel-finance/relaychain-subql'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://regnet4-relay-rpc.parallel.fi'
  genesisHash: '0xf86591aeaa54b7221022a95b298d1bdf68603cb689d555bd4d686ecc4a83ba2c'
  # dictionary: 'https://api.subquery.network/sq/subquery/kusama-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 15000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
