specVersion: 1.0.0
name: kusama-subql
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '^1'
  query:
    name: '@subql/query'
    version: '^1'
description: Parallel kusama subql indexing service
repository: 'https://github.com/parallel-finance/relaychain-subql'
schema:
  file: ./schema.graphql
network:
  chainId: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: 'wss://kusama-rpc.polkadot.io'
dataSources:
  - kind: substrate/Runtime
    startBlock: 13400007
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleCrowdloanContributed
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed
